### ISSUE TITLE
card expiry date 

### ISSUE THREAD

**Issue by Danielguang** [card-io/card.io-Android-SDK#167] opened 2016-10-07 06:53 UTC
I used  card-io -cordova plugin,
but I cant get expiry date from my card.only card number info
, i have include the scanEpiry in my js files;
My card :Bank of China,
Color: grey
Card Type: MasterCard

**Comment by Danielguang** [comment] 2016-10-07 06:57
Also test in Andorid Native, not supported

**Comment by Danielguang** [comment] 2016-10-07 09:47
card.io  libaray :5.4.2

**Comment by netcleaner** [comment] 2016-10-28 00:41
I also can't read the expiry date.
I used lastest version SDK. And set the setting like below.

scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_EXPIRY, true);
scanIntent.putExtra(CardIOActivity.EXTRA_SCAN_EXPIRY, true);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_CVV, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_POSTAL_CODE, false); // default: false
scanIntent.putExtra(CardIOActivity.EXTRA_RESTRICT_POSTAL_CODE_TO_NUMERIC_ONLY, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_CARDHOLDER_NAME, false);

**Comment by lkorth** [comment] 2017-02-03 15:11
Duplicate of #119

**Closed by lkorth** 2017-02-03 15:11 UTC
