### ISSUE TITLE
how can i import card-io example with card.io-Android-sdk in Eclipse?

### ISSUE THREAD

**Issue by pranaypatel512** [card-io/card.io-Android-SDK#69] opened 2015-07-09 06:17 UTC
i want to import card-io example with card.io-Android-sdk in Eclipse?

**Comment by tomwhipple** [comment] 2015-07-31 17:40
This is not a bug report.

I'd suggest Googling around or asking on [StackOverflow](https://stackoverflow.com) how to convert Gradle projects to Eclipse.

But given that the Android community seems to be moving to Android Studio, it might be more effective to take advantage of the latest tools.

**Closed by tomwhipple** 2015-07-31 17:40 UTC
