### ISSUE TITLE
After Denying to grant Camera permission, Card Details form appears twice

### ISSUE THREAD

**Issue by sleepylee** [card-io/card.io-Android-SDK#182] opened 2017-03-09 10:37 UTC
### General information

* SDK/Library version: 5.5.0
* Android Version and Device: Nexus 6 (Android 7.0)

### Issue description
As been described from the title, we are observing this issue by:
- Denying to grant Camera access in order to use Scanning card function
- The Card Details form appears as an expected behavior from CardIO lib.
- Press Cancel.
- Observing that another Card Details form re-appear again.

**Comment by lkorth** [comment] 2017-03-09 15:37
Duplicate of #150

**Closed by lkorth** 2017-03-09 15:37 UTC

**Comment by bsc1780** [comment] 2017-03-09 16:01
[](url)
