### ISSUE TITLE
5.4.2 Not Working Moto X Play With Marshmallow

### ISSUE THREAD

**Issue by govardhan88** [card-io/card.io-Android-SDK#174] opened 2016-12-06 08:52 UTC
I/card.io: Checking hardware support...
 I/card.io: card.io 5.4.2 09/27/2016 11:38:46 -0500
D/card.io: Loaded card.io decider library.
 D/card.io:     nUseNeon(): true
 D/card.io:     nUseTegra():false
E/art: No implementation found for boolean io.card.payment.CardScanner.nUseX86() (tried Java_io_card_payment_CardScanner_nUseX86 and Java_io_card_payment_CardScanner_nUseX86__)
 E/card.io: Failed to load native library: No implementation found for boolean io.card.payment.CardScanner.nUseX86() (tried Java_io_card_payment_CardScanner_nUseX86 and Java_io_card_payment_CardScanner_nUseX86__)
 W/card.io: - Processor type is not supported

**Comment by radiim** [comment] 2016-12-15 13:39
Hi,

same problem here on my Samsung Galaxy On Nxt (SM-G610F) running Android 6.0.1

I am trying to use 5.4.2. Logs -
12-15 17:57:08.567 8073-8073/com.example.myapp.cardioandroidsdk E/card.io: Failed to load native library: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.example.myapp.cardioandroidsdk-1/lib/arm/libcardioDecider.so"...
12-15 17:57:08.567 8073-8073/com.example.myapp.cardioandroidsdk W/card.io: - Processor type is not supported

However 5.4.1 and 5.4.0 work fine.

thanks

**Comment by loudenvier** [comment] 2017-01-03 20:08
This issue is already open here #166

**Comment by lkorth** [comment] 2017-01-09 22:09
Closing as duplicate of #165, #166, #168, #170

**Closed by lkorth** 2017-01-09 22:09 UTC
